version: '3.8'

services:
  
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong@Password"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data: