name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
    paths:
    - SQL/**

jobs:

  Update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup SQL server
      run:  docker compose up -d


    - name: Restore dependencies
      run: dotnet restore ./runner

    - name: Build project
      run: dotnet build ./runner --no-restore

    - name: Run project
      run: dotnet run --project ./runner
